-- MySQL Script generated by MySQL Workbench
-- 06/01/15 20:14:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ds3_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ds3_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ds3_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ds3_db` ;

-- -----------------------------------------------------
-- Table `ds3_db`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds3_db`.`materias_primas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`materias_primas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds3_db`.`matpri_fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`matpri_fornecedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fornecedor_id` INT NOT NULL,
  `materia_prima_id` INT NOT NULL,
  `preco` DOUBLE(10,2) NULL,
  `diasprazo` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rel_matprifornecedor_tbl_fornecedor_idx` (`fornecedor_id` ASC),
  INDEX `fk_rel_matprifornecedor_tbl_materiaprima1_idx` (`materia_prima_id` ASC),
  CONSTRAINT `fk_rel_matprifornecedor_tbl_fornecedor`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `ds3_db`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rel_matprifornecedor_tbl_materiaprima1`
    FOREIGN KEY (`materia_prima_id`)
    REFERENCES `ds3_db`.`materias_primas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds3_db`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds3_db`.`fabrica_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`fabrica_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produto_id` INT NOT NULL,
  `materia_prima_id` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_fabricaproduto_tbl_produto1_idx` (`produto_id` ASC),
  INDEX `fk_tbl_fabricaproduto_tbl_materiaprima1_idx` (`materia_prima_id` ASC),
  CONSTRAINT `fk_tbl_fabricaproduto_tbl_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ds3_db`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_fabricaproduto_tbl_materiaprima1`
    FOREIGN KEY (`materia_prima_id`)
    REFERENCES `ds3_db`.`materias_primas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `ds3_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `datacadastro` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds3_db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds3_db`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fornecedor_id` INT NOT NULL,
  `datapedido` DATE NOT NULL,
  `dataentrega` DATE NULL,
  `status_id` INT NOT NULL,
  `dataprevisaoentrega` DATE NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_pedido_tbl_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_tbl_pedido_tbl_status1_idx` (`status_id` ASC),
  INDEX `fk_tbl_pedido_tbl_fornecedor1_idx` (`fornecedor_id` ASC),
  CONSTRAINT `fk_tbl_pedido_tbl_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `ds3_db`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `ds3_db`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `ds3_db`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds3_db`.`pedido_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`pedido_itens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `materia_prima_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_pedidoitem_tbl_pedido1_idx` (`pedido_id` ASC),
  INDEX `fk_tbl_pedidoitem_tbl_materiaprima1_idx` (`materia_prima_id` ASC),
  CONSTRAINT `fk_tbl_pedidoitem_tbl_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `ds3_db`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedidoitem_tbl_materiaprima1`
    FOREIGN KEY (`materia_prima_id`)
    REFERENCES `ds3_db`.`materias_primas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ds3_db`.`estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ds3_db`.`estoques` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `materia_prima_id` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_estoque_tbl_materiaprima1_idx` (`materia_prima_id` ASC),
  CONSTRAINT `fk_tbl_estoque_tbl_materiaprima1`
    FOREIGN KEY (`materia_prima_id`)
    REFERENCES `ds3_db`.`materias_primas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
